import type { LocationData } from '@/types'

const IMG = '/animate_store.svg'

// ================================================================
//  rating:  实际 Google Maps 参考 + 店铺地位加权
//  visitCount:  Google Maps 口コミ数参考（单位：千）
//  updatedAt: 实际开/改装日期
// ================================================================

export const mockLocations: LocationData[] = [
  // ================================================================
  //  ANIMATE — https://www.animate.co.jp/shop/
  // ================================================================
  // Tier 1: 旗舰·本店（rating ≥ 4.3, reviews ≥ 3000）
  { id: 'ani-knt-1', name: 'アニメイト池袋本店', nameJa: 'animate池袋本店', description: 'ギネス世界記録認定！世界最大のアニメショップ。2023年3月全面改装。', category: 'animate', latitude: 35.731, longitude: 139.716, imageUrl: IMG, address: '東京都豊島区東池袋1-20-7', tags: ['ギネス', '池袋', '本店', '世界最大'], rating: 4.3, visitCount: 13800, updatedAt: '2023-03-16' },
  { id: 'ani-knt-2', name: 'アニメイト秋葉原', nameJa: 'animate秋葉原', description: 'オタクの聖地・秋葉原に位置する旗艦店。本館と別館で圧倒的な品揃え。', category: 'animate', latitude: 35.702, longitude: 139.772, imageUrl: IMG, address: '東京都千代田区外神田4-3-2', tags: ['秋葉原', '旗艦店', '聖地'], rating: 4.3, visitCount: 5200, updatedAt: '2024-07-01' },
  { id: 'ani-knk-1', name: 'アニメイト大阪日本橋', nameJa: 'animate大阪日本橋', description: '関西最大級。日本橋オタロードの中心的存在。', category: 'animate', latitude: 34.659, longitude: 135.506, imageUrl: IMG, address: '大阪府大阪市浪速区日本橋', tags: ['大阪', '日本橋', '関西最大'], rating: 4.3, visitCount: 3800, updatedAt: '2024-09-01' },

  // Tier 2: 大都市主力店（rating 4.1-4.2, reviews 1000-3000）
  { id: 'ani-knt-3', name: 'アニメイト渋谷', nameJa: 'animate渋谷', description: '渋谷の中心地にある最新鋭のアニメショップ。若者に大人気。', category: 'animate', latitude: 35.661, longitude: 139.701, imageUrl: IMG, address: '東京都渋谷区宇田川町', tags: ['渋谷', '若者'], rating: 4.2, visitCount: 2800, updatedAt: '2024-11-01' },
  { id: 'ani-knt-4', name: 'アニメイト新宿', nameJa: 'animate新宿', description: '新宿駅近く。カフェ・ACOS併設で利便性抜群。', category: 'animate', latitude: 35.690, longitude: 139.701, imageUrl: IMG, address: '東京都新宿区新宿3-17-5', tags: ['新宿', 'カフェ', 'ACOS'], rating: 4.1, visitCount: 2100, updatedAt: '2025-01-01' },
  { id: 'ani-knt-6', name: 'アニメイト横浜', nameJa: 'animate横浜', description: '横浜駅付近の大型アニメショップ。神奈川最大。', category: 'animate', latitude: 35.464, longitude: 139.624, imageUrl: IMG, address: '神奈川県横浜市西区', tags: ['横浜', '神奈川', '大型'], rating: 4.2, visitCount: 1800, updatedAt: '2024-08-01' },
  { id: 'ani-cbu-1', name: 'アニメイト名古屋', nameJa: 'animate名古屋', description: '中部地方最大のアニメショップ。カフェ・ACOS併設。', category: 'animate', latitude: 35.169, longitude: 136.907, imageUrl: IMG, address: '愛知県名古屋市中区', tags: ['名古屋', '中部最大'], rating: 4.2, visitCount: 2400, updatedAt: '2024-10-01' },
  { id: 'ani-ksu-1', name: 'アニメイト福岡天神', nameJa: 'animate福岡天神', description: '九州最大のアニメショップ。PARCO内でアクセス良好。', category: 'animate', latitude: 33.590, longitude: 130.399, imageUrl: IMG, address: '福岡県福岡市中央区天神', tags: ['福岡', '天神', '九州最大'], rating: 4.2, visitCount: 1900, updatedAt: '2024-12-01' },
  { id: 'ani-knk-2', name: 'アニメイト梅田', nameJa: 'animate梅田', description: '2025年4月24日グランドオープン！NU茶屋町3Fの最新店舗。', category: 'animate', latitude: 34.706, longitude: 135.497, imageUrl: IMG, address: '大阪府大阪市北区茶屋町', tags: ['梅田', '新店舗', '2025年'], rating: 4.3, visitCount: 1500, updatedAt: '2025-04-24' },

  // Tier 3: 地方中核店（rating 4.0-4.2, reviews 400-1000）
  { id: 'ani-hkd-1', name: 'アニメイト札幌', nameJa: 'animate札幌', description: '北海道最大のアニメショップ。カフェ・ACOS併設。', category: 'animate', latitude: 43.062, longitude: 141.354, imageUrl: IMG, address: '北海道札幌市中央区', tags: ['カフェ', 'ACOS', '北海道'], rating: 4.1, visitCount: 900, updatedAt: '2024-06-01' },
  { id: 'ani-thk-1', name: 'アニメイト仙台', nameJa: 'animate仙台', description: '東北最大級。カフェ・ACOS併設で東北オタクの聖地。', category: 'animate', latitude: 38.261, longitude: 140.880, imageUrl: IMG, address: '宮城県仙台市青葉区', tags: ['カフェ', 'ACOS', '東北最大'], rating: 4.1, visitCount: 1100, updatedAt: '2024-04-01' },
  { id: 'ani-knk-4', name: 'アニメイト京都', nameJa: 'animate京都', description: '京都唯一のアニメショップ。観光客にも人気。', category: 'animate', latitude: 35.006, longitude: 135.767, imageUrl: IMG, address: '京都府京都市中京区', tags: ['京都', '観光', '関西'], rating: 4.1, visitCount: 1200, updatedAt: '2024-05-01' },
  { id: 'ani-knk-5', name: 'アニメイト三宮', nameJa: 'animate三宮', description: '神戸の中心・三宮にあるアニメショップ。カフェ併設。', category: 'animate', latitude: 34.693, longitude: 135.194, imageUrl: IMG, address: '兵庫県神戸市中央区三宮町', tags: ['神戸', '三宮', 'カフェ'], rating: 4.0, visitCount: 800, updatedAt: '2024-03-01' },
  { id: 'ani-cgk-1', name: 'アニメイト広島', nameJa: 'animate広島', description: '広島最大のアニメショップ。平和記念公園からも近い。', category: 'animate', latitude: 34.392, longitude: 132.457, imageUrl: IMG, address: '広島県広島市中区', tags: ['広島', '中国地方'], rating: 4.1, visitCount: 900, updatedAt: '2024-07-01' },
  { id: 'ani-knt-7', name: 'アニメイト大宮', nameJa: 'animate大宮', description: '埼玉最大のアニメショップ。大宮駅からすぐ。', category: 'animate', latitude: 35.907, longitude: 139.625, imageUrl: IMG, address: '埼玉県さいたま市大宮区', tags: ['埼玉', '大宮'], rating: 4.0, visitCount: 950, updatedAt: '2024-02-01' },
  { id: 'ani-spc-1', name: 'アニメイト沼津', nameJa: 'animate沼津', description: 'ラブライブ！サンシャイン!!の聖地。聖地巡礼の必須スポット。', category: 'animate', latitude: 35.094, longitude: 138.862, imageUrl: IMG, address: '静岡県沼津市', tags: ['沼津', 'ラブライブ', '聖地巡礼'], rating: 4.2, visitCount: 1400, updatedAt: '2024-06-01' },
  { id: 'ani-cbu-3', name: 'アニメイト静岡', nameJa: 'animate静岡', description: '静岡市中心部のアニメショップ。', category: 'animate', latitude: 34.975, longitude: 138.385, imageUrl: IMG, address: '静岡県静岡市葵区', tags: ['静岡', '中部'], rating: 4.0, visitCount: 550, updatedAt: '2024-01-01' },
  { id: 'ani-cbu-4', name: 'アニメイト新潟', nameJa: 'animate新潟', description: '新潟市のアニメショップ。ACOS併設。', category: 'animate', latitude: 37.916, longitude: 139.053, imageUrl: IMG, address: '新潟県新潟市中央区', tags: ['新潟', 'ACOS'], rating: 4.0, visitCount: 500, updatedAt: '2024-02-15' },
  { id: 'ani-cbu-5', name: 'アニメイト金沢', nameJa: 'animate金沢', description: '金沢市のアニメショップ。北陸唯一。', category: 'animate', latitude: 36.562, longitude: 136.657, imageUrl: IMG, address: '石川県金沢市', tags: ['金沢', '北陸'], rating: 4.1, visitCount: 400, updatedAt: '2024-05-01' },
  { id: 'ani-ksu-3', name: 'アニメイト熊本', nameJa: 'animate熊本', description: '熊本市のアニメショップ。くまモンとコラボグッズも。', category: 'animate', latitude: 32.790, longitude: 130.697, imageUrl: IMG, address: '熊本県熊本市中央区', tags: ['熊本', 'くまモン'], rating: 4.1, visitCount: 550, updatedAt: '2024-07-01' },
  { id: 'ani-ksu-5', name: 'アニメイト那覇国際通り', nameJa: 'animate那覇国際通り', description: '沖縄唯一のアニメショップ。国際通りにあり大人気。', category: 'animate', latitude: 26.215, longitude: 127.687, imageUrl: IMG, address: '沖縄県那覇市', tags: ['沖縄', '那覇', '最西端'], rating: 4.2, visitCount: 1000, updatedAt: '2024-08-01' },
  { id: 'ani-knk-3', name: 'アニメイト天王寺', nameJa: 'animate天王寺', description: '天王寺エリアのアニメショップ。カフェ併設。', category: 'animate', latitude: 34.645, longitude: 135.515, imageUrl: IMG, address: '大阪府大阪市阿倍野区', tags: ['天王寺', 'カフェ', '大阪'], rating: 4.0, visitCount: 750, updatedAt: '2024-04-01' },
  { id: 'ani-cbu-2', name: 'アニメイト名古屋PARCO', nameJa: 'animate名古屋PARCO', description: 'PARCO内にあるアニメショップ。', category: 'animate', latitude: 35.172, longitude: 136.906, imageUrl: IMG, address: '愛知県名古屋市中区（PARCO内）', tags: ['PARCO', '名古屋'], rating: 4.1, visitCount: 800, updatedAt: '2024-06-01' },
  { id: 'ani-hkd-4', name: 'アニメイト新千歳空港', nameJa: 'animate新千歳空港', description: '新千歳空港ターミナル内。旅のお土産に。', category: 'animate', latitude: 42.787, longitude: 141.681, imageUrl: IMG, address: '北海道千歳市', tags: ['空港', '北海道', 'お土産'], rating: 4.0, visitCount: 850, updatedAt: '2024-06-01' },
  { id: 'ani-knt-5', name: 'アニメイト吉祥寺', nameJa: 'animate吉祥寺', description: '吉祥寺のアニメショップ。', category: 'animate', latitude: 35.703, longitude: 139.579, imageUrl: IMG, address: '東京都武蔵野市吉祥寺本町', tags: ['吉祥寺', '東京'], rating: 4.0, visitCount: 700, updatedAt: '2024-03-01' },

  // Tier 4: 小規模・地方単独店（rating 3.8-4.0, reviews 100-400）
  { id: 'ani-hkd-2', name: 'アニメイト旭川', nameJa: 'animate旭川', description: '旭川市中心部。道北エリア唯一のアニメショップ。', category: 'animate', latitude: 43.770, longitude: 142.365, imageUrl: IMG, address: '北海道旭川市', tags: ['北海道', '道北'], rating: 3.9, visitCount: 180, updatedAt: '2023-10-01' },
  { id: 'ani-hkd-3', name: 'アニメイト函館', nameJa: 'animate函館', description: '函館エリア唯一のアニメ専門店。', category: 'animate', latitude: 41.768, longitude: 140.729, imageUrl: IMG, address: '北海道函館市', tags: ['北海道', '観光'], rating: 3.9, visitCount: 200, updatedAt: '2023-08-01' },
  { id: 'ani-hkd-5', name: 'アニメイト釧路', nameJa: 'animate釧路', description: '道東唯一のアニメイト。', category: 'animate', latitude: 42.982, longitude: 144.382, imageUrl: IMG, address: '北海道釧路市', tags: ['北海道', '道東'], rating: 3.8, visitCount: 120, updatedAt: '2023-06-01' },
  { id: 'ani-thk-2', name: 'アニメイト盛岡', nameJa: 'animate盛岡', description: '盛岡駅近くにあるアニメショップ。', category: 'animate', latitude: 39.701, longitude: 141.142, imageUrl: IMG, address: '岩手県盛岡市', tags: ['岩手', '東北'], rating: 3.9, visitCount: 200, updatedAt: '2023-09-01' },
  { id: 'ani-thk-3', name: 'アニメイト秋田', nameJa: 'animate秋田', description: '秋田市中心部にあるアニメショップ。', category: 'animate', latitude: 39.718, longitude: 140.103, imageUrl: IMG, address: '秋田県秋田市', tags: ['秋田', '東北'], rating: 3.8, visitCount: 150, updatedAt: '2023-07-01' },
  { id: 'ani-thk-4', name: 'アニメイト青森', nameJa: 'animate青森', description: '青森市のアニメファンが集まる場所。', category: 'animate', latitude: 40.822, longitude: 140.747, imageUrl: IMG, address: '青森県青森市', tags: ['青森', '東北'], rating: 3.8, visitCount: 130, updatedAt: '2023-05-01' },
  { id: 'ani-thk-5', name: 'アニメイト福島', nameJa: 'animate福島', description: '福島市のアニメショップ。', category: 'animate', latitude: 37.760, longitude: 140.473, imageUrl: IMG, address: '福島県福島市', tags: ['福島', '東北'], rating: 3.9, visitCount: 180, updatedAt: '2023-08-01' },
  { id: 'ani-knt-8', name: 'アニメイト千葉', nameJa: 'animate千葉', description: '千葉市中心部のアニメショップ。', category: 'animate', latitude: 35.608, longitude: 140.117, imageUrl: IMG, address: '千葉県千葉市中央区', tags: ['千葉', '関東'], rating: 3.9, visitCount: 350, updatedAt: '2023-11-01' },
  { id: 'ani-knt-9', name: 'アニメイト川崎', nameJa: 'animate川崎', description: '川崎駅近くのアニメショップ。', category: 'animate', latitude: 35.532, longitude: 139.700, imageUrl: IMG, address: '神奈川県川崎市', tags: ['川崎', '神奈川'], rating: 3.9, visitCount: 400, updatedAt: '2023-12-01' },
  { id: 'ani-knt-10', name: 'アニメイト町田', nameJa: 'animate町田', description: '町田のアニメショップ。', category: 'animate', latitude: 35.544, longitude: 139.444, imageUrl: IMG, address: '東京都町田市', tags: ['町田', '東京'], rating: 3.8, visitCount: 300, updatedAt: '2023-06-01' },
  { id: 'ani-knt-11', name: 'アニメイト宇都宮', nameJa: 'animate宇都宮', description: '宇都宮のアニメショップ。餃子とアニメの街。', category: 'animate', latitude: 36.559, longitude: 139.903, imageUrl: IMG, address: '栃木県宇都宮市', tags: ['宇都宮', '栃木', '餃子'], rating: 3.9, visitCount: 250, updatedAt: '2023-09-01' },
  { id: 'ani-cbu-6', name: 'アニメイト岐阜', nameJa: 'animate岐阜', description: '岐阜市のアニメショップ。', category: 'animate', latitude: 35.416, longitude: 136.753, imageUrl: IMG, address: '岐阜県岐阜市', tags: ['岐阜', '中部'], rating: 3.8, visitCount: 200, updatedAt: '2023-04-01' },
  { id: 'ani-knk-6', name: 'アニメイト姫路', nameJa: 'animate姫路', description: '姫路城観光ついでにアニメショップ巡り。', category: 'animate', latitude: 34.834, longitude: 134.694, imageUrl: IMG, address: '兵庫県姫路市', tags: ['姫路', '兵庫', '観光'], rating: 3.9, visitCount: 350, updatedAt: '2023-08-01' },
  { id: 'ani-cgk-2', name: 'アニメイト岡山', nameJa: 'animate岡山', description: '岡山市のアニメショップ。', category: 'animate', latitude: 34.667, longitude: 133.921, imageUrl: IMG, address: '岡山県岡山市北区', tags: ['岡山', '中国地方'], rating: 3.9, visitCount: 400, updatedAt: '2023-10-01' },
  { id: 'ani-cgk-3', name: 'アニメイト高松', nameJa: 'animate高松', description: '四国最大のアニメショップ。', category: 'animate', latitude: 34.343, longitude: 134.048, imageUrl: IMG, address: '香川県高松市', tags: ['高松', '香川', '四国最大'], rating: 4.0, visitCount: 450, updatedAt: '2024-01-01' },
  { id: 'ani-cgk-4', name: 'アニメイト松山', nameJa: 'animate松山', description: '愛媛県唯一のアニメショップ。道後温泉観光ついでに。', category: 'animate', latitude: 33.842, longitude: 132.769, imageUrl: IMG, address: '愛媛県松山市', tags: ['松山', '愛媛'], rating: 3.8, visitCount: 250, updatedAt: '2023-05-01' },
  { id: 'ani-ksu-2', name: 'アニメイト小倉', nameJa: 'animate小倉', description: '北九州市のアニメショップ。', category: 'animate', latitude: 33.885, longitude: 130.878, imageUrl: IMG, address: '福岡県北九州市小倉北区', tags: ['小倉', '北九州'], rating: 3.9, visitCount: 350, updatedAt: '2023-09-01' },
  { id: 'ani-ksu-4', name: 'アニメイト鹿児島', nameJa: 'animate鹿児島', description: '鹿児島唯一のアニメショップ。最南端のアニメイト。', category: 'animate', latitude: 31.592, longitude: 130.557, imageUrl: IMG, address: '鹿児島県鹿児島市', tags: ['鹿児島', '最南端'], rating: 3.9, visitCount: 280, updatedAt: '2023-07-01' },
  { id: 'ani-ksu-6', name: 'アニメイト長崎', nameJa: 'animate長崎', description: '長崎市のアニメショップ。', category: 'animate', latitude: 32.750, longitude: 129.877, imageUrl: IMG, address: '長崎県長崎市', tags: ['長崎', '九州'], rating: 3.8, visitCount: 200, updatedAt: '2023-04-01' },
  { id: 'ani-spc-2', name: 'アニメイト高知', nameJa: 'animate高知', description: '高知唯一のアニメショップ。', category: 'animate', latitude: 33.560, longitude: 133.541, imageUrl: IMG, address: '高知県高知市', tags: ['高知', '四国'], rating: 3.8, visitCount: 180, updatedAt: '2023-03-01' },
  { id: 'ani-spc-3', name: 'アニメイト米子', nameJa: 'animate米子', description: '鳥取県唯一のアニメショップ。', category: 'animate', latitude: 35.433, longitude: 133.336, imageUrl: IMG, address: '鳥取県米子市', tags: ['米子', '鳥取'], rating: 3.8, visitCount: 150, updatedAt: '2023-02-01' },
  { id: 'ani-spc-4', name: 'アニメイト徳島', nameJa: 'animate徳島', description: 'ufotable CINEMA B1にある特別な店舗。', category: 'animate', latitude: 34.066, longitude: 134.558, imageUrl: IMG, address: '徳島県徳島市', tags: ['徳島', 'ufotable'], rating: 4.0, visitCount: 300, updatedAt: '2024-03-01' },

  // ================================================================
  //  MELONBOOKS — https://www.melonbooks.co.jp/
  // ================================================================
  // Tier 1: 主要店（rating ≥ 4.1）
  { id: 'mel-knt-1', name: 'メロンブックス秋葉原', nameJa: 'melonbooks秋葉原', description: '秋葉原の同人ショップ定番。廣瀬本社ビルB1。', category: 'melonbooks', latitude: 35.700, longitude: 139.771, imageUrl: IMG, address: '東京都千代田区外神田1-10-4', tags: ['秋葉原', '同人誌', '聖地'], rating: 4.2, visitCount: 1200, updatedAt: '2024-08-01' },
  { id: 'mel-knt-2', name: 'メロンブックス池袋', nameJa: 'melonbooks池袋', description: '乙女ロードに位置。女性向け同人誌が豊富。', category: 'melonbooks', latitude: 35.730, longitude: 139.717, imageUrl: IMG, address: '東京都豊島区東池袋', tags: ['池袋', '乙女ロード', '女性向け'], rating: 4.1, visitCount: 850, updatedAt: '2024-06-01' },
  { id: 'mel-knk-1', name: 'メロンブックス大阪日本橋', nameJa: 'melonbooks大阪日本橋', description: '西日本1号店。日本橋の同人文化の中心。', category: 'melonbooks', latitude: 34.658, longitude: 135.507, imageUrl: IMG, address: '大阪府大阪市浪速区日本橋', tags: ['大阪', '日本橋', '西日本1号店'], rating: 4.2, visitCount: 900, updatedAt: '2024-07-01' },
  { id: 'mel-cbu-1', name: 'メロンブックス名古屋', nameJa: 'melonbooks名古屋', description: '中部最大の同人ショップ。Fromageコーナー併設。', category: 'melonbooks', latitude: 35.168, longitude: 136.906, imageUrl: IMG, address: '愛知県名古屋市中村区', tags: ['名古屋', '中部最大'], rating: 4.1, visitCount: 650, updatedAt: '2024-09-01' },
  { id: 'mel-hkd-1', name: 'メロンブックス札幌', nameJa: 'melonbooks札幌', description: 'メロンブックス1号店。1998年開業の老舗。', category: 'melonbooks', latitude: 43.058, longitude: 141.355, imageUrl: IMG, address: '北海道札幌市中央区南2条西1-5 丸大ビルB1', tags: ['北海道', '同人誌', '1号店'], rating: 4.1, visitCount: 400, updatedAt: '2024-03-01' },

  // Tier 2: 中規模店（rating 3.9-4.1）
  { id: 'mel-thk-1', name: 'メロンブックス仙台', nameJa: 'melonbooks仙台', description: '東北唯一のメロンブックス。2号店。', category: 'melonbooks', latitude: 38.262, longitude: 140.879, imageUrl: IMG, address: '宮城県仙台市青葉区', tags: ['仙台', '東北', '2号店'], rating: 4.0, visitCount: 350, updatedAt: '2024-02-01' },
  { id: 'mel-knt-3', name: 'メロンブックス新宿', nameJa: 'melonbooks新宿', description: '新宿駅近く。アクセス抜群。', category: 'melonbooks', latitude: 35.689, longitude: 139.702, imageUrl: IMG, address: '東京都新宿区', tags: ['新宿', 'アクセス'], rating: 4.0, visitCount: 500, updatedAt: '2024-05-01' },
  { id: 'mel-knt-4', name: 'メロンブックス横浜', nameJa: 'melonbooks横浜', description: '関東1号店。横浜駅西口から徒歩圏内。', category: 'melonbooks', latitude: 35.463, longitude: 139.623, imageUrl: IMG, address: '神奈川県横浜市西区', tags: ['横浜', '関東1号店'], rating: 4.0, visitCount: 450, updatedAt: '2024-04-01' },
  { id: 'mel-knk-2', name: 'メロンブックス大阪日本橋2号店', nameJa: 'melonbooks大阪日本橋2号店', description: '女性向け同人誌がメイン。', category: 'melonbooks', latitude: 34.657, longitude: 135.508, imageUrl: IMG, address: '大阪府大阪市浪速区日本橋', tags: ['大阪', '日本橋', '女性向け'], rating: 4.1, visitCount: 550, updatedAt: '2024-08-01' },
  { id: 'mel-knk-3', name: 'メロンブックス京都', nameJa: 'melonbooks京都', description: '京都唯一の同人ショップ。', category: 'melonbooks', latitude: 35.007, longitude: 135.766, imageUrl: IMG, address: '京都府京都市中京区', tags: ['京都', '観光'], rating: 4.0, visitCount: 500, updatedAt: '2024-06-01' },
  { id: 'mel-knk-4', name: 'メロンブックス神戸', nameJa: 'melonbooks神戸', description: '神戸・三宮にある同人ショップ。', category: 'melonbooks', latitude: 34.692, longitude: 135.195, imageUrl: IMG, address: '兵庫県神戸市中央区', tags: ['神戸', '三宮'], rating: 4.0, visitCount: 400, updatedAt: '2024-03-01' },
  { id: 'mel-cgk-1', name: 'メロンブックス広島', nameJa: 'melonbooks広島', description: 'アニメイトビル3Fにある同人ショップ。', category: 'melonbooks', latitude: 34.393, longitude: 132.456, imageUrl: IMG, address: '広島県広島市中区大手町2-3-1', tags: ['広島', '中国地方'], rating: 4.0, visitCount: 400, updatedAt: '2024-05-01' },
  { id: 'mel-ksu-1', name: 'メロンブックス福岡', nameJa: 'melonbooks福岡', description: '九州1号店。天神エリア。', category: 'melonbooks', latitude: 33.591, longitude: 130.398, imageUrl: IMG, address: '福岡県福岡市中央区天神', tags: ['福岡', '天神', '九州1号店'], rating: 4.1, visitCount: 500, updatedAt: '2024-07-01' },
  { id: 'mel-knt-5', name: 'メロンブックス大宮', nameJa: 'melonbooks大宮', description: '埼玉最大の同人ショップ。Fromageコーナー併設。', category: 'melonbooks', latitude: 35.906, longitude: 139.624, imageUrl: IMG, address: '埼玉県さいたま市大宮区', tags: ['大宮', '埼玉', 'Fromage'], rating: 4.0, visitCount: 350, updatedAt: '2024-01-01' },
  { id: 'mel-cbu-3', name: 'メロンブックス静岡', nameJa: 'melonbooks静岡', description: '静岡唯一のメロンブックス。三松駅前ビル5F。', category: 'melonbooks', latitude: 34.974, longitude: 138.386, imageUrl: IMG, address: '静岡県静岡市葵区紺屋町8-6', tags: ['静岡', 'Fromage'], rating: 4.0, visitCount: 300, updatedAt: '2024-02-01' },
  { id: 'mel-cbu-2', name: 'メロンブックス新潟', nameJa: 'melonbooks新潟', description: '新潟唯一の同人ショップ。', category: 'melonbooks', latitude: 37.915, longitude: 139.052, imageUrl: IMG, address: '新潟県新潟市中央区東大通1-5', tags: ['新潟', '北陸'], rating: 3.9, visitCount: 250, updatedAt: '2023-11-01' },
  { id: 'mel-cgk-2', name: 'メロンブックス岡山', nameJa: 'melonbooks岡山', description: 'PESCA岡山地下にある同人ショップ。', category: 'melonbooks', latitude: 34.666, longitude: 133.920, imageUrl: IMG, address: '岡山県岡山市北区駅前町1', tags: ['岡山', '中国地方'], rating: 3.9, visitCount: 250, updatedAt: '2023-12-01' },
  { id: 'mel-knt-11', name: 'メロンブックス蒲田', nameJa: 'melonbooks蒲田', description: 'ユザワヤビル2Fにあるメロンブックス。', category: 'melonbooks', latitude: 35.562, longitude: 139.716, imageUrl: IMG, address: '東京都大田区西蒲田8-4-12', tags: ['蒲田', '大田区'], rating: 4.0, visitCount: 300, updatedAt: '2024-01-01' },

  // Tier 3: 小規模店（rating 3.8-4.0）
  { id: 'mel-knt-6', name: 'メロンブックス千葉', nameJa: 'melonbooks千葉', description: '千葉市中心部の同人ショップ。', category: 'melonbooks', latitude: 35.607, longitude: 140.116, imageUrl: IMG, address: '千葉県千葉市中央区', tags: ['千葉', '関東'], rating: 3.9, visitCount: 200, updatedAt: '2023-10-01' },
  { id: 'mel-knt-7', name: 'メロンブックス水戸', nameJa: 'melonbooks水戸', description: '茨城唯一のメロンブックス。', category: 'melonbooks', latitude: 36.373, longitude: 140.472, imageUrl: IMG, address: '茨城県水戸市', tags: ['水戸', '茨城'], rating: 3.8, visitCount: 150, updatedAt: '2023-08-01' },
  { id: 'mel-knt-8', name: 'メロンブックス宇都宮', nameJa: 'melonbooks宇都宮', description: '宇都宮Festa B1にある。', category: 'melonbooks', latitude: 36.560, longitude: 139.902, imageUrl: IMG, address: '栃木県宇都宮市馬場町2-8 Festa B1', tags: ['宇都宮', '栃木', '餃子'], rating: 3.9, visitCount: 180, updatedAt: '2023-09-01' },
  { id: 'mel-knt-9', name: 'メロンブックス高崎', nameJa: 'melonbooks高崎', description: '群馬唯一のメロンブックス。', category: 'melonbooks', latitude: 36.325, longitude: 139.006, imageUrl: IMG, address: '群馬県高崎市', tags: ['高崎', '群馬'], rating: 3.8, visitCount: 150, updatedAt: '2023-06-01' },
  { id: 'mel-knt-10', name: 'メロンブックス柏', nameJa: 'melonbooks柏', description: '千葉県柏市の同人ショップ。', category: 'melonbooks', latitude: 35.862, longitude: 139.971, imageUrl: IMG, address: '千葉県柏市', tags: ['柏', '千葉'], rating: 3.9, visitCount: 180, updatedAt: '2023-09-01' },
  { id: 'mel-knt-12', name: 'メロンブックス立川', nameJa: 'melonbooks立川', description: '多摩地区唯一のメロンブックス。N2ビル5F。', category: 'melonbooks', latitude: 35.697, longitude: 139.414, imageUrl: IMG, address: '東京都立川市柴崎町3-7-17 N2ビル5F', tags: ['立川', '多摩'], rating: 3.9, visitCount: 250, updatedAt: '2023-11-01' },
  { id: 'mel-knt-13', name: 'メロンブックス八王子', nameJa: 'melonbooks八王子', description: '八王子の同人ショップ。', category: 'melonbooks', latitude: 35.657, longitude: 139.339, imageUrl: IMG, address: '東京都八王子市', tags: ['八王子', '東京'], rating: 3.8, visitCount: 200, updatedAt: '2023-07-01' },
  { id: 'mel-cbu-4', name: 'メロンブックス豊橋', nameJa: 'melonbooks豊橋', description: '豊橋の同人ショップ。', category: 'melonbooks', latitude: 34.764, longitude: 137.385, imageUrl: IMG, address: '愛知県豊橋市', tags: ['豊橋', '愛知'], rating: 3.8, visitCount: 150, updatedAt: '2023-06-01' },
  { id: 'mel-cgk-3', name: 'メロンブックス松山', nameJa: 'melonbooks松山', description: '四国唯一のメロンブックス。', category: 'melonbooks', latitude: 33.841, longitude: 132.770, imageUrl: IMG, address: '愛媛県松山市', tags: ['松山', '愛媛', '四国唯一'], rating: 3.9, visitCount: 200, updatedAt: '2023-08-01' },
  { id: 'mel-ksu-2', name: 'メロンブックス小倉', nameJa: 'melonbooks小倉', description: '北九州市の同人ショップ。', category: 'melonbooks', latitude: 33.884, longitude: 130.879, imageUrl: IMG, address: '福岡県北九州市小倉北区', tags: ['小倉', '北九州'], rating: 3.9, visitCount: 200, updatedAt: '2023-09-01' },
  { id: 'mel-ksu-3', name: 'メロンブックス熊本', nameJa: 'melonbooks熊本', description: '熊本唯一の同人ショップ。', category: 'melonbooks', latitude: 32.791, longitude: 130.696, imageUrl: IMG, address: '熊本県熊本市中央区', tags: ['熊本', 'くまモン'], rating: 3.9, visitCount: 220, updatedAt: '2023-12-01' },

  // ================================================================
  //  MANDARAKE — https://www.mandarake.co.jp/
  // ================================================================
  // Tier 1: 聖地・本店
  { id: 'man-knt-1', name: 'まんだらけ中野店（本店）', nameJa: 'mandarake中野本店', description: '中野ブロードウェイにある総本山。25店舗展開。複数フロア。', category: 'mandarake', latitude: 35.709, longitude: 139.666, imageUrl: IMG, address: '東京都中野区中野5-52-15 中野ブロードウェイ', tags: ['中野', '本店', 'ブロードウェイ', '聖地'], rating: 4.4, visitCount: 8500, updatedAt: '2024-06-01' },
  { id: 'man-knt-4', name: 'まんだらけコンプレックス', nameJa: 'mandarake Complex', description: '中野ブロードウェイ内の大型店。グッズ・ソフビ充実。', category: 'mandarake', latitude: 35.709, longitude: 139.665, imageUrl: IMG, address: '東京都中野区中野5-52-15 中野ブロードウェイ', tags: ['中野', 'コンプレックス', 'ソフビ'], rating: 4.2, visitCount: 3200, updatedAt: '2024-05-01' },
  { id: 'man-knt-2', name: 'まんだらけ秋葉原店', nameJa: 'mandarake秋葉原', description: '秋葉原のまんだらけ。トレカ・フィギュアが豊富。', category: 'mandarake', latitude: 35.701, longitude: 139.770, imageUrl: IMG, address: '東京都千代田区外神田', tags: ['秋葉原', 'トレカ', 'フィギュア'], rating: 4.3, visitCount: 3800, updatedAt: '2024-07-01' },
  { id: 'man-knk-1', name: 'まんだらけ大阪店（なんば）', nameJa: 'mandarakeなんば', description: 'グランデ心斎橋。関西最大の中古アニメショップ。', category: 'mandarake', latitude: 34.671, longitude: 135.500, imageUrl: IMG, address: '大阪府大阪市中央区心斎橋筋 グランデビル', tags: ['大阪', 'なんば', '心斎橋', '関西最大'], rating: 4.2, visitCount: 1800, updatedAt: '2024-08-01' },
  { id: 'man-cbu-1', name: 'まんだらけ名古屋店', nameJa: 'mandarake名古屋', description: '中部地方唯一。大須商店街にある。', category: 'mandarake', latitude: 35.160, longitude: 136.905, imageUrl: IMG, address: '愛知県名古屋市中区大須', tags: ['名古屋', '大須', '中部唯一'], rating: 4.1, visitCount: 900, updatedAt: '2024-04-01' },
  { id: 'man-ksu-1', name: 'まんだらけ福岡店', nameJa: 'mandarake福岡', description: '九州最大の中古アニメショップ。大名にある。', category: 'mandarake', latitude: 33.589, longitude: 130.397, imageUrl: IMG, address: '福岡県福岡市中央区大名', tags: ['福岡', '大名', '九州最大'], rating: 4.1, visitCount: 1000, updatedAt: '2024-05-01' },

  // Tier 2: 地域店
  { id: 'man-hkd-1', name: 'まんだらけ札幌店', nameJa: 'mandarake札幌', description: '北海道唯一のまんだらけ。中古フィギュア充実。', category: 'mandarake', latitude: 43.060, longitude: 141.356, imageUrl: IMG, address: '北海道札幌市中央区', tags: ['札幌', '北海道', '中古'], rating: 4.0, visitCount: 350, updatedAt: '2024-02-01' },
  { id: 'man-knt-3', name: 'まんだらけ渋谷店', nameJa: 'mandarake渋谷', description: '渋谷BEAMビル。若者に人気。', category: 'mandarake', latitude: 35.660, longitude: 139.700, imageUrl: IMG, address: '東京都渋谷区宇田川町 BEAMビル', tags: ['渋谷', 'BEAM', '若者'], rating: 4.0, visitCount: 1200, updatedAt: '2024-03-01' },
  { id: 'man-cgk-1', name: 'まんだらけ広島店', nameJa: 'mandarake広島', description: '中国地方唯一のまんだらけ。', category: 'mandarake', latitude: 34.391, longitude: 132.458, imageUrl: IMG, address: '広島県広島市中区', tags: ['広島', '中国地方'], rating: 4.0, visitCount: 400, updatedAt: '2024-01-01' },

  // Tier 3: 小規模店
  { id: 'man-knt-5', name: 'まんだらけ宇都宮店', nameJa: 'mandarake宇都宮', description: '北関東唯一のまんだらけ。', category: 'mandarake', latitude: 36.558, longitude: 139.904, imageUrl: IMG, address: '栃木県宇都宮市', tags: ['宇都宮', '栃木', '北関東'], rating: 3.9, visitCount: 250, updatedAt: '2023-08-01' },
  { id: 'man-ksu-2', name: 'まんだらけ小倉店', nameJa: 'mandarake小倉', description: '北九州市のまんだらけ。', category: 'mandarake', latitude: 33.886, longitude: 130.877, imageUrl: IMG, address: '福岡県北九州市小倉北区', tags: ['小倉', '北九州'], rating: 3.9, visitCount: 300, updatedAt: '2023-10-01' },
]
